import { SidebarProvider, SidebarTrigger } from './ui/sidebar'
import { AppSidebar } from "@/components/ui/app-sidebar"
import { Outlet } from 'react-router-dom'

const Layout = () => {
  return (
    <div className='bg-gradient-to-br from-background to-muted'>
        <SidebarProvider>
          <AppSidebar />
          <main className='min-h-screen container mx-auto px-4 py-8'>
            <SidebarTrigger />
            <Outlet />
          </main>
        </SidebarProvider>
        <footer className='border-t backdrop-blur py-12 supports-[backdrop-filter]:bg-background/60'>
          <div className='container mx-auto px-4 text-center text-gray-500'>
            <p>All forecasts on this website are generated by NUS-SDA and are provided for informational purposes only.</p>
          </div>
        </footer>
    </div>
  )
}

export default Layout