import { SidebarProvider, SidebarTrigger } from './ui/sidebar'
import { AppSidebar } from "@/components/ui/app-sidebar"
import { Outlet } from 'react-router-dom'

const Layout = () => {
  return (
    <div className='min-h-screen'>
        <SidebarProvider>
          <AppSidebar />
          <main className='min-h-screen container mx-auto px-4 py-8'>
            <SidebarTrigger className="mb-4 text-[#4670bc] hover:bg-[#61adde]/10 border-[#99b6c4]" />
            <Outlet />
          </main>
        </SidebarProvider>
        <footer className='border-t border-[#99b6c4]/20 bg-gradient-to-r from-[#61adde]/5 to-[#99b6c4]/5 py-8'>
          <div className='container mx-auto px-4 text-center text-[#4670bc]'>
            <p>All forecasts on this website are generated by NUS-SDA and are provided for informational purposes only.</p>
          </div>
        </footer>
    </div>
  )
}

export default Layout